import { z } from "zod";

/**
 * Selector strategies, ordered by priority. The recorder always tries to pick
 * the highest priority strategy that unambiguously identifies one element.
 */
export const SELECTOR_STRATEGIES = [
  "role",
  "label",
  "placeholder",
  "text",
  "testid",
  "name",
  "id",
  "css",
  "xpath"
] as const;

export type SelectorStrategy = (typeof SELECTOR_STRATEGIES)[number];

export const SELECTOR_PRIORITY: SelectorStrategy[] = [...SELECTOR_STRATEGIES];

export const SelectorSchema = z
  .object({
    strategy: z.enum(SELECTOR_STRATEGIES),
    /** Primary selector value. For strategy "role" this is unused; use role+name. */
    value: z.string().min(1).optional(),
    role: z.string().min(1).optional(),
    name: z.string().min(1).optional(),
    /** Raw CSS (or XPath) fallback used only when the primary selector fails. */
    fallback: z.string().min(1).nullish(),
    /** Logical page/tab identifier the element belongs to. */
    pageId: z.string().min(1).default("main"),
    /** Same-origin frame selector, when the element lives inside an iframe. */
    frame: z.string().min(1).nullish()
  })
  .superRefine((sel, ctx) => {
    if (sel.strategy === "role") {
      if (!sel.role) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "selector.role is required when strategy is 'role'"
        });
      }
    } else if (!sel.value) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `selector.value is required when strategy is '${sel.strategy}'`
      });
    }
  });

export type Selector = z.infer<typeof SelectorSchema>;

/** Raw information about a DOM element, collected by the injected recorder script. */
export interface ElementInfo {
  tag: string;
  type?: string | null;
  role?: string | null;
  accessibleName?: string | null;
  label?: string | null;
  placeholder?: string | null;
  text?: string | null;
  testId?: string | null;
  nameAttr?: string | null;
  /** The `value` attribute, which makes a radio inside a group addressable. */
  valueAttr?: string | null;
  id?: string | null;
  cssPath?: string | null;
  xpath?: string | null;
  /**
   * Per-strategy uniqueness, computed in the page: true when the candidate
   * selector matched exactly one element.
   */
  unique?: Partial<Record<SelectorStrategy, boolean>> | null;
  pageId?: string | null;
  frame?: string | null;
}

interface Candidate {
  strategy: SelectorStrategy;
  value?: string;
  role?: string;
  name?: string;
}

function isUnique(info: ElementInfo, strategy: SelectorStrategy): boolean {
  // Absence of information is treated as "not proven unique" for the
  // ambiguity-sensitive strategies, and as unique for structural ones.
  const flag = info.unique?.[strategy];
  if (typeof flag === "boolean") return flag;
  return strategy === "css" || strategy === "xpath" || strategy === "id" || strategy === "testid";
}

/**
 * Accessible names and label texts longer than this are rejected as selector
 * values: past this length a label is usually a whole sentence of page copy
 * rather than a stable identifier.
 */
export const MAX_TEXTUAL_SELECTOR_LENGTH = 80;

/**
 * Detects text that changes without the page changing — prices, monthly
 * instalments, interest rates, discounts. A selector built on such text works
 * when recorded and silently breaks at the next price update, so a stable
 * attribute is preferred even though it ranks lower in the strategy order.
 */
export function looksVolatile(text: string): boolean {
  if (/[€$£¥]/.test(text)) return true;
  // An amount such as "1.749,00" or "57.26".
  if (/\d[.,]\d{2}(\D|$)/.test(text)) return true;
  // A percentage such as "10,99%".
  if (/\d(?:[.,]\d+)?\s*%/.test(text)) return true;
  return false;
}

function isUsableText(value: string | null | undefined): value is string {
  if (!value) return false;
  const trimmed = value.trim();
  if (trimmed.length === 0 || trimmed.length > MAX_TEXTUAL_SELECTOR_LENGTH) return false;
  return !looksVolatile(trimmed);
}

/**
 * Recognises ids generated by a UI framework, which change on every render and
 * are therefore useless in a saved workflow. Covers React `useId` (`:r0:`,
 * `_r_e_`), Radix (`radix-:r1:`), MUI (`mui-1234`) and purely numeric ids.
 */
export function isGeneratedId(id: string): boolean {
  const value = id.trim();
  if (value.length === 0) return true;
  // React useId and Radix emit colons; nothing hand-written normally does.
  if (value.includes(":")) return true;
  // Wrapped in underscores with only short fragments inside, e.g. `_r_e_`.
  if (/^_[a-z0-9_]{0,10}_$/i.test(value)) return true;
  // Purely numeric, e.g. `1234`.
  if (/^\d+$/.test(value)) return true;
  // A short prefix followed by a counter, e.g. `mui-1234`, `el7`, `a1`.
  if (/^[a-z]{1,4}[-_]?\d{1,6}$/i.test(value)) return true;
  return false;
}

/** A checkbox or radio is addressable by name + value even inside a group. */
function nameAndValueSelector(info: ElementInfo): string | null {
  const type = (info.type ?? "").toLowerCase();
  if (info.tag.toLowerCase() !== "input") return null;
  if (type !== "radio" && type !== "checkbox") return null;
  if (!info.nameAttr || !info.valueAttr) return null;
  return `input[name="${info.nameAttr}"][value="${info.valueAttr}"]`;
}

function buildCandidates(info: ElementInfo): Candidate[] {
  const candidates: Candidate[] = [];

  if (info.role && isUsableText(info.accessibleName)) {
    candidates.push({ strategy: "role", role: info.role, name: info.accessibleName.trim() });
  }
  if (isUsableText(info.label)) {
    candidates.push({ strategy: "label", value: info.label.trim() });
  }
  if (isUsableText(info.placeholder)) {
    candidates.push({ strategy: "placeholder", value: info.placeholder.trim() });
  }
  if (isUsableText(info.text)) {
    candidates.push({ strategy: "text", value: info.text.trim() });
  }
  if (info.testId) {
    candidates.push({ strategy: "testid", value: info.testId });
  }
  // Preferred over a bare name for grouped inputs: `name` alone matches the whole
  // radio group and would be rejected as ambiguous.
  const nameValue = nameAndValueSelector(info);
  if (nameValue) {
    candidates.push({ strategy: "css", value: nameValue });
  }
  if (info.nameAttr) {
    candidates.push({ strategy: "name", value: info.nameAttr });
  }
  if (info.id && !isGeneratedId(info.id)) {
    candidates.push({ strategy: "id", value: info.id });
  }
  if (info.cssPath) {
    candidates.push({ strategy: "css", value: info.cssPath });
  }
  if (info.xpath) {
    candidates.push({ strategy: "xpath", value: info.xpath });
  }

  return candidates.sort(
    (a, b) => SELECTOR_PRIORITY.indexOf(a.strategy) - SELECTOR_PRIORITY.indexOf(b.strategy)
  );
}

/** Builds a raw CSS/XPath string usable as a fallback selector. */
export function buildFallback(info: ElementInfo): string | null {
  // For a grouped input the value is what disambiguates it.
  const nameValue = nameAndValueSelector(info);
  if (nameValue) return nameValue;
  if (info.nameAttr) {
    return `${info.tag.toLowerCase()}[name='${info.nameAttr}']`;
  }
  if (info.id && !isGeneratedId(info.id)) {
    return `#${info.id}`;
  }
  if (info.cssPath) return info.cssPath;
  if (info.xpath) return info.xpath;
  return null;
}

/**
 * Picks the best selector for an element following the documented priority.
 * Returns null when no candidate can identify the element at all: the caller
 * must then refuse to record the action instead of guessing.
 */
export function chooseSelector(info: ElementInfo): Selector | null {
  const candidates = buildCandidates(info);
  const unique = candidates.filter((c) => isUnique(info, c.strategy));
  const chosen = unique[0];
  if (!chosen) return null;

  const fallbackCandidate = buildFallback(info);
  const fallback =
    fallbackCandidate && fallbackCandidate !== chosen.value ? fallbackCandidate : null;

  return SelectorSchema.parse({
    strategy: chosen.strategy,
    value: chosen.value,
    role: chosen.role,
    name: chosen.name,
    fallback,
    pageId: info.pageId ?? "main",
    frame: info.frame ?? null
  });
}

/** Human readable description of a selector, safe to show in logs and UI. */
export function describeSelector(sel: Selector): string {
  if (sel.strategy === "role") {
    return `role=${sel.role}${sel.name ? `[name="${sel.name}"]` : ""}`;
  }
  return `${sel.strategy}=${sel.value}`;
}
